CREATE TABLE user (
    ID INT(100) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    CORREO VARCHAR(200) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    ID_ADMIN INT(100) NOT NULL,
    FOREIGN KEY (ID_ADMIN) REFERENCES admin(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE lab (
    ID INT(100) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL
);

CREATE TABLE product (
    ID INT(100) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    ID_LAB INT(100) NOT NULL,
    IMG VARCHAR(255) NOT NULL,
    FOREIGN KEY (ID_LAB) REFERENCES lab(ID)
);

CREATE TABLE compra (
    ID INT(100) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_USER INT(100) NOT NULL,
    ID_PRODUCT INT(100) NOT NULL,
    ID_ADMIN INT(100) NOT NULL,
    FECHA_COMPRA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CANTIDAD INT(10) NOT NULL,
    FOREIGN KEY (ID_USER) REFERENCES user(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (ID_PRODUCT) REFERENCES product(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (ID_ADMIN) REFERENCES admin(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE user_product (
    ID INT(100) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_USER INT NOT NULL,
    ID_PRODUCT INT NOT NULL,
    UNIQUE (ID_USER, ID_PRODUCT),
    FOREIGN KEY (ID_USER) REFERENCES user(ID)
        ON DELETE CASCADE,
    FOREIGN KEY (ID_PRODUCT) REFERENCES product(ID)
        ON DELETE CASCADE
);

CREATE TABLE promo (
    ID INT(100) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_USER_PRODUCT INT(100) NOT NULL,
    COMPRADOS INT(10) NOT NULL,
    FALTANTES INT(10) NOT NULL DEFAULT 3,
    RESET BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (ID_USER_PRODUCT) REFERENCES user_product(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE admin (
    ID INT(100) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    MAIL VARCHAR(200) NOT NULL,
    PW TEXT NOT NULL,
    ROLL INT(3) NOT NULL DEFAULT 2
);

CREATE TABLE history (
    ID INT(100) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_USER INT(100) NOT NULL,
    ID_PRODUCT INT(100) NOT NULL,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_ADMIN INT(100) NOT NULL,
    FOREIGN KEY (ID_ADMIN) REFERENCES admin(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (ID_USER) REFERENCES user(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (ID_PRODUCT) REFERENCES product(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);